#! /bin/sh

sxhkd &
setxkbmap -layout us -option ctrl:nocaps
sh ~/scripts/screens.sh
betterlockscreen -l &
xrdb .Xresources
wal -i ~/Wallpapers/ && python .config/qutebrowser/scripts/qutebrowser_reload.py
polybar secondisplay &
polybar example &
polybar bar & 
polybar bar2 &
polybar bar3 & 
compton -CGb --config compton.conf &
dunst &

# This is my monitor setup, I am using 12 workspaces because I want to be a weeb with some japanese words as icons 

bspc monitor HDMI-0 -d 1 2 3 4 5 6 
bspc monitor DVI-I-0 -d 7 8 9 10 11

# These are my program launching rules. 

bspc rule -a TelegramDesktop desktop=7
bspc rule -a telegram-desktop desktop=7
bspc rule -a discord desktop=7
bspc rule -a qutebrowser desktop=1
bspc rule -a mpv desktop=8 state=floating follow=on


bspc config border_width         3
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus 	button1


